language: node_js
node_js:
  - "node"

cache: npm

# temporary fix until greenkeeper works with `npm ci`
install: case $TRAVIS_BRANCH in greenkeeper*) npm i;; *) npm ci;; esac;

# Build the website, instead of running tests
script:
  - npm run build

# Push to Github Pages
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
